rules:
  - rule_text: "pipeline: generate_steps, refine_steps, evaluate"
    source: "manual"
    goal_type: "research"
    goal_category: "ai_research"
    difficulty: "medium"

  - goal_type: "reasoning"
    agent_name: "cot_generator"
    rule_text: "Break the question into three logical steps."
    source: "manual"
    difficulty: "medium"
    focus_area: "planning"

  - goal_type: "math"
    agent_name: "math_solver"
    rule_text: "Simplify the expression symbolically before evaluating."
    source: "manual"
    difficulty: "hard"
    focus_area: "symbolic"

  - goal_type: "science"
    agent_name: "hypothesis_agent"
    rule_text: "Include both a theory and an example in the hypothesis."
    source: "manual"
    difficulty: "medium"
    focus_area: "scientific_reasoning"

  - goal_type: "philosophy"
    agent_name: "debate_agent"
    rule_text: "Argue both sides before choosing a stance."
    source: "manual"
    difficulty: "hard"
    focus_area: "dialectic"

  - goal_type: "ethics"
    agent_name: "judge_agent"
    rule_text: "Consider utilitarian and deontological views."
    source: "manual"
    difficulty: "medium"
    focus_area: "moral reasoning"

  - goal_type: "strategy"
    agent_name: "planner"
    rule_text: "Identify short-term and long-term goals separately."
    source: "manual"
    difficulty: "medium"
    focus_area: "strategic_planning"

  - goal_type: "reasoning"
    agent_name: "refiner"
    rule_text: "Eliminate unsupported assumptions."
    source: "manual"
    difficulty: "easy"
    focus_area: "logical_pruning"

  - goal_type: "creativity"
    agent_name: "hypothesis_agent"
    rule_text: "Include at least one surprising idea."
    source: "manual"
    difficulty: "medium"
    focus_area: "novelty"

  - goal_type: "language"
    agent_name: "verbal_agent"
    rule_text: "Avoid passive voice and favor active constructions."
    source: "manual"
    difficulty: "easy"
    focus_area: "clarity"

  - goal_type: "planning"
    agent_name: "method_planner"
    rule_text: "Check for redundancy in the selected steps."
    source: "manual"
    difficulty: "medium"
    focus_area: "optimization"

  - goal_type: "analysis"
    agent_name: "reflector"
    rule_text: "Identify what changed and why in the second run."
    source: "manual"
    difficulty: "hard"
    focus_area: "meta_reasoning"

  - goal_type: "research"
    agent_name: "literature_agent"
    rule_text: "Look for at least two corroborating sources."
    source: "manual"
    difficulty: "medium"
    focus_area: "evidence"

  - goal_type: "training"
    agent_name: "ripper"
    rule_text: "Use MR.Q scores to select contrasting examples."
    source: "manual"
    difficulty: "hard"
    focus_area: "data_selection"

  - goal_type: "learning"
    agent_name: "symbolic_optimizer"
    rule_text: "Prioritize rules that consistently lead to higher scores."
    source: "manual"
    difficulty: "hard"
    focus_area: "symbolic_tuning"

  - goal_type: "debugging"
    agent_name: "reflector"
    rule_text: "Log all agent inputs and outputs at each stage."
    source: "manual"
    difficulty: "easy"
    focus_area: "traceability"

  - rule_text: "pipeline: generate_steps, refine_steps, evaluate"
    source: "manual"
    goal_type: "research"
    goal_category: "ai_research"
    difficulty: "medium"

  - rule_text: "pipeline: cot_generator, scorer"
    source: "manual"
    goal_type: "research"
    difficulty: "medium"

  - rule_text: "hint: emphasize_self_improvement"
    source: "lookahead"
    goal_category: "ai_research"
    strategy: "reasoning"