# config/agents/evolution.yaml
defaults:
  - prompt_refiner: default

agent:
  name: evolution
  strategy: grafting  # Options: grafting, simplification, inspiration, out_of_the_box
  use_grafting: true