import json
from pathlib import Path
from typing import List, Dict, Optional, Union
from collections import Counter

# Required for loading Hugging Face datasets
from datasets import load_dataset


class ARMDataLoader:
    def __init__(
        self,
        dataset_name: str = "aqua_rat",
        subset: Optional[str] = None,
        split: str = "train",
        memory=None,
        logger=None,
    ):
        self.dataset_name = dataset_name
        self.subset = subset
        self.split = split
        self.memory = memory
        self.logger = logger

        # Format tokens
        self.format_tokens = {
            "direct": "<Direct>",
            "short_cot": "<Short_CoT>",
            "code": "<Code>",
            "long_cot": "<Long_CoT>",
        }
        self.format_end_tokens = {
            "direct": "</Direct>",
            "short_cot": "</Short_CoT>",
            "code": "</Code>",
            "long_cot": "</Long_CoT>",
        }
        self._debug_count = 0
        self.dataset = None

    def adapt(self, context: dict):
        """Main method: loads → converts → saves into context"""
        print(f"[INFO] Loading dataset '{self.dataset_name}'...")
        self.dataset = load_dataset(self.dataset_name, self.subset, split=self.split)
        print(f"[INFO] Loaded {len(self.dataset)} samples.")

        dpo_samples = []
        difficulty = context.get("difficulty")

        for sample in self.dataset:
            pairs = self.build_preference_pairs(sample, difficulty=difficulty)
            dpo_samples.extend(pairs)

        context["dpo_samples"] = dpo_samples
        print(
            f"[INFO] Generated {len(dpo_samples)} DPO preference pairs and saved to context."
        )

    def load_dataset(self):
        """Load dataset from Hugging Face."""
        try:
            self.dataset = load_dataset(
                self.dataset_name, self.subset, split=self.split
            )
            print(
                f"[INFO] Loaded {len(self.dataset)} samples from Hugging Face dataset '{self.dataset_name}'"
            )
        except Exception as e:
            raise RuntimeError(
                f"Failed to load dataset '{self.dataset_name}': {str(e)}"
            )

    def _detect_difficulty(self, question: str) -> str:
        """Basic heuristic to infer difficulty based on question length."""
        words = question.split()
        if len(words) < 20:
            return "easy"
        elif len(words) < 50:
            return "medium"
        else:
            return "hard"

    def generate_direct(self, answer: str) -> str:
        return f"The answer is {answer}."

    def generate_short_cot(self, question: str, answer: str) -> str:
        return (
            "Let me think briefly:\n"
            + "Step 1: Understand the question.\n"
            + "Step 2: Apply basic logic.\n"
            + f"Final Answer: {answer}"
        )

    def generate_code(self, question: str, answer: str) -> str:
        return (
            "def solve():\n"
            "    # Placeholder code generated by GPT-4o\n"
            f"    return '{answer}'\n"
            "solve()\n"
            f"# Output: {answer}"
        )

    def generate_long_cot(self, question: str, answer: str) -> str:
        return (
            "Let's analyze this step-by-step:\n\n"
            "1. Read the question carefully.\n"
            "2. Identify key information.\n"
            "3. Consider multiple approaches.\n"
            "4. Evaluate thoroughly.\n"
            "...\n"
            "Reflection: This approach ensures correctness by exploring multiple paths.\n"
            f"Final Answer: {answer}"
        )

    def summarize_difficulties(self):
        """Summarize how many questions fall into each difficulty level."""
        counts = Counter()
        for sample in self.dataset:
            question = sample.get("question", "")
            detected = self._detect_difficulty(question)
            counts[detected] += 1
        print("[SUMMARY] Detected difficulty distribution:", dict(counts))
        return counts

    def print_samples_by_difficulty(self, count_per_level=3):
        """Print a few examples per difficulty level for debugging."""
        buckets = {"easy": [], "medium": [], "hard": []}
        for sample in self.dataset:
            question = sample.get("question", "")
            difficulty = self._detect_difficulty(question)
            if len(buckets[difficulty]) < count_per_level:
                buckets[difficulty].append(question)

        for diff, questions in buckets.items():
            print(f"\n--- {diff.upper()} EXAMPLES ---")
            for q in questions:
                print(f"- {q}")

    def wrap_with_format_token(self, text: str, fmt: str) -> str:
        """Wrap response in format token."""
        start = self.format_tokens.get(fmt, "")
        end = self.format_end_tokens.get(fmt, "")
        if not start or not end:
            return text
        return f"{start}\n{text}\n{end}"

    def build_preference_pairs(
        self, sample: Dict, difficulty: Optional[str] = None
    ) -> List[Dict]:
        """
        Build preference pairs from one sample using format-based reward shaping.

        Args:
            sample: AQuA-Rat style sample with question, options, rationale, correct answer
            difficulty: Optional override for task difficulty

        Returns:
            List of DPO-style preference samples
        """
        question = sample.get("question", "").strip()
        options = sample.get("options", [])
        ground_truth = sample.get("correct", "").strip()

        if not question or not ground_truth:
            return []

        # Use sample difficulty or fallback to basic logic
        difficulty = difficulty or self._detect_difficulty(question)

        preferred_formats = []
        non_preferred_formats = []

        # Define format priority by difficulty
        if difficulty == "easy":
            preferred_formats = ["direct", "short_cot", "code"]
            non_preferred_formats = ["long_cot"]
        elif difficulty == "medium":
            preferred_formats = ["short_cot", "code"]
            non_preferred_formats = ["direct", "long_cot"]
        elif difficulty == "hard":
            preferred_formats = ["long_cot", "code"]
            non_preferred_formats = ["direct", "short_cot"]
        else:
            preferred_formats = ["short_cot", "code"]
            non_preferred_formats = ["direct", "long_cot"]

        # Generate all four formats per question
        direct_answer = self.generate_direct(ground_truth)
        short_cot_answer = self.generate_short_cot(question, ground_truth)
        code_answer = self.generate_code(question, ground_truth)
        long_cot_answer = self.generate_long_cot(question, ground_truth)

        # Map format names to generated responses
        format_to_response = {
            "direct": direct_answer,
            "short_cot": short_cot_answer,
            "code": code_answer,
            "long_cot": long_cot_answer,
        }

        # Filter out empty responses
        valid_formats = [
            fmt for fmt in format_to_response if format_to_response[fmt]
        ]
        format_to_response = {
            k: v for k, v in format_to_response.items() if k in valid_formats
        }

        # Build all possible pairs
        pairs = []
        for pref in preferred_formats:
            p_resp = format_to_response.get(pref)
            if not p_resp:
                continue
            for non_pref in non_preferred_formats:
                np_resp = format_to_response.get(non_pref)
                if not np_resp:
                    continue
                pairs.append(
                    {
                        "prompt": question,
                        "chosen": self.wrap_with_format_token(p_resp, pref),
                        "rejected": self.wrap_with_format_token(np_resp, non_pref),
                        "preferred_format": pref,
                        "rejected_format": non_pref,
                        "difficulty": difficulty,
                    }
                )

        return pairs