# config/scoring/paper_review.yaml
output_format: simple

dimensions:
  - name: relevance
    file: relevance
    weight: 1.5
    extra_data: { parser: numeric }

  - name: novelty
    file: novelty
    weight: 1.2
    extra_data: { parser: numeric }

  - name: implementability
    file: implementability
    weight: 1.0 that scoring mix in
    extra_data: { parser: numeric }
