# config/scoring/reflection.yaml
dimensions:
  - name: correctness
    file: correctness
    weight: 1.2
    extra_data: { parser: numeric }

  - name: feasibility
    file: feasibility
    weight: 1.1
    extra_data: { parser: numeric }

  - name: insightfulness
    file: insightfulness
    weight: 1.3
    extra_data: { parser: numeric }

  - name: alignment
    file: alignment
    weight: 1.0
    extra_data: { parser: numeric }
