scoring_profile: step_quality
prompt_dir: prompts/step_quality
scorer: llm
output_format: cor
dimensions:
  - name: correctness
    file: correctness.txt
    weight: 1.2
    extra_data: { parser: numeric }

  - name: clarity
    file: clarity.txt
    weight: 1.1
    extra_data: { parser: numeric }

  - name: relevance
    file: relevance.txt
    weight: 1.2
    extra_data: { parser: numeric }

  # - name: generality
  #   file: generality.txt
  #   weight: 1.0
  #   extra_data: { parser: numeric }

  # - name: usefulness
  #   file: usefulness.txt
  #   weight: 1.3
  #   extra_data: { parser: numeric }

  # - name: specificity
  #   file: specificity.txt
  #   weight: 1.0
  #   extra_data: { parser: numeric }

  - name: novelty
    file: novelty.txt
    weight: 0.8
    extra_data: { parser: numeric }

  # - name: dependency_alignment
  #   file: dependency_alignment.txt
  #   weight: 1.0
  #   extra_data: { parser: numeric }
