# config/scorer/svm/default.yaml
name: svm
model_type: svm
model_version: v1
evaluator: svn
target_type: document
dimensions: 
  - alignment
  - clarity
  - implementability
  - novelty
  - relevance
