# config/config.yaml
defaults:
  - _self_
  - db: postgres
  - agents/automind
  - agents/survey
  - agents/search_orchestrator
  - logging/json_logger

goal:
  goal_text: "How could an autonomous AI lab iteratively improve its own hypotheses using symbolic rules and evaluation feedback?"
  goal_type: "automind"
  goal_category: "ai_research"
  focus_area: "ai"
  strategy: "reasoning"
  difficulty: "hard"
  expected_formats:
    - "tree_of_thought"
    - "strategy_plan"

symbolic:
  enabled: false  # set to false to skip symbolic rule application
  rules_file: "config/rules/rules.yaml"
  enable_db_rules: false # load rules from the database
  match_priority:
    - goal_id
    - pipeline_run_id
    - metadata
  metadata_match_mode: partial   # options: exact, partial, off
  allow_fallback: true           # if no ID matches, allow metadata fallback

planner:
  name: planner
  enabled: false
  cls: stephanie.agents.planner.PipelinePlannerAgent
  dots_enabled: true
  lookahead_enabled: true

dynamic:
  name: lookahead
  enabled: false
  cls: stephanie.agents.lookahead.LookaheadAgent

post_judgment:
  name: pipeline_judge
  enabled: false
  cls: stephanie.agents.pipeline_judge.PipelineJudgeAgent

paths:
  prompts: ${hydra:runtime.cwd}/prompts

report:
  generate_report: true
  path: ${hydra:runtime.cwd}/reports

web_search:
  engine: "searxng"
  instance_url: "http://localhost:8080"


embeddings:
  model: "mxbai-embed-large"
  dimension: 1024
  endpoint: "http://localhost:11434/api/embeddings"

pipeline:
  name: default_pipeline
  description: "Default hypothesis generation and refinement pipeline"
  stages:
     - name: survey
       cls: stephanie.agents.survey.SurveyAgent
       enabled: true
       iterations: 1
     - name: search_orchestrator
       cls: stephanie.agents.search_orchestrator.SearchOrchestratorAgent
       enabled: true
       iterations: 1
