# config/config.yaml
defaults:
  - _self_
  - db: postgres
  - logging/json_logger
  - agents/generation
  - agents/reflection
  - agents/ranking
  - agents/evolution
  - agents/meta_review
  - agents/proximity
  - agents/literature
  - agents/supervisor

report:
  generate_report: true
  path: reports/
  
embeddings:
  model: "mxbai-embed-large"
  dimension: 1024
  endpoint: "http://localhost:11434/api/embeddings"

pipeline:
  name: default_pipeline
  description: "Default hypothesis generation and refinement pipeline"
  stages:
    - name: literature
      enabled: true
      iterations: 1
    - name: generation
      enabled: true
      iterations: 1
    - name: reflection
      enabled: true
      iterations: 1
    - name: ranking
      enabled: true
      iterations: 1
    - name: proximity
      enabled: true
      iterations: 1 
    - name: evolution
      enabled: true
      iterations: 2
    - name: meta_review
      enabled: true
      iterations: 1
