defaults:
  - _self_
  - db: postgres
  - agents/arxiv_search
  - agents/document_loader
  - agents/document_profiler
  - agents/paper_score
  - agents/knowledge_loader
  - agents/document_mrq_inference
  - agents/sicql_mrq_inference
  - agents/document_mrq_trainer
  - agents/hrm_trainer
  - agents/document_mrq_inference
  - agents/sicql_mrq_trainer
  - agents/document_ebt_trainer
  - agents/document_ebt_inference
  - agents/document_reward_scorer
  - agents/document_svm_trainer
  - agents/document_svm_inference
  - agents/document_embedding_backfill
  - agents/document_llm_inference
  - agents/knowledge_db_loader
  - agents/gild_trainer
  - agents/ethics
  - agents/scoring_memcube
  - agents/scoring_policy
  - agents/policy_analyzer
  - agents/pipeline_comparison
  - agents/pipeline_judge
  - agents/scoring_report
  - agents/hnet
  - agents/score_comparison
  - agents/score_energy_comparison
  - agents/score_analysis
  - agents/policy_synthesis
  - agents/epistemic_plan_hrm_trainer
  - agents/epistemic_plan_executor
  - logging/json_logger

embeddings:
  backend: hnet

goal:
  goal_text: Develop a strategy for the AI to Identify high-quality reasoning patterns in previous traces and reuse them.
  goal_type: "tactical"
  goal_category: "meta_learning"
  focus_area: "self_improvement"
  strategy: "stepwise_decomposition"
  difficulty: "medium-high"
  expected_formats:
    - "symbolic_prompt_plan"
    - "stepwise_reasoning_trace"
    - "annotated_score_vector"

post_judgment:
  name: pipeline_judge
  enabled: false
  cls: stephanie.agents.pipeline_judge.PipelineJudgeAgent

paths:
  prompts: ${hydra:runtime.cwd}/prompts

report:
  save_context_result: false
  generate_report: false
  path: ${hydra:runtime.cwd}/reports

web_search:
  engine: "searxng"
  instance_url: "http://localhost:8080"

pipeline:
  name: policy
  tag: "search_arxiv"
  description: "Search Arxiv for papers related to a goal"
  stages:

    - name: epistemic_plan_executor
      description: "Execute the epistemic plan to generate hypotheses"
      cls: stephanie.agents.epistemic_plan_executor.EpistemicPlanExecutorAgent
      enabled: true
      iterations: 1

    - name: epistemic_plan_hrm_trainer  
      description: "Train the HRM model to predict document values based on epistemic plans"
      cls: stephanie.agents.epistemic_plan_hrm_trainer.EpistemicPlanHRMTrainerAgent
      enabled: true
      iterations: 1

