# config/config.yaml
defaults:
  - _self_
  - db: postgres
  - agents/cot_dspy_generator
  - agents/cot_generator
  - agents/debate
  - agents/dots_planner
  - agents/evolution
  - agents/general_reasoner
  - agents/generation
  - agents/generic
  - agents/judge
  - agents/literature
  - agents/literature_ranking
  - agents/lookahead
  - agents/meta_review
  - agents/mrq_strategy
  - agents/pipeline_judge
  - agents/prompt_tuning
  - agents/proximity
  - agents/ranking
  - agents/refiner
  - agents/reflection
  - agents/reflection_delta
  - agents/review
  - agents/sharpening
  # - agents/strategy_selector
  - agents/symbolic_optimizer
  - logging/json_logger

# The goal of the pipeline, e.g., "Generate a hypothesis about the impact of climate change on biodiversity."
# This is a placeholder and should be replaced with the actual goal.
goal: 
  goal_text: "Will AI ever be able to reprogram itself?"
  goal_type: research # Options: math, science, commonsense, factoid, ethical, policy, planning, creative, other, research

dynamic:
  name: lookahead
  enabled: false
  cls: co_ai.agents.lookahead.LookaheadAgent

post_judgment:
  name: pipeline_judge
  enabled: true
  cls: co_ai.agents.pipeline_judge.PipelineJudgeAgent


paths:
  prompts: ${hydra:runtime.cwd}/prompts

report:
  generate_report: true
  path: ${hydra:runtime.cwd}/reports

web_search:
  engine: "searxng"
  instance_url: "http://localhost:8080"


embeddings:
  model: "mxbai-embed-large"
  dimension: 1024
  endpoint: "http://localhost:11434/api/embeddings"

pipeline:
  name: default_pipeline
  description: "Default hypothesis generation and refinement pipeline"
  stages:
     - name: generation
       cls: co_ai.agents.generation.GenerationAgent
       enabled: true
       iterations: 1
     - name: proximity
       cls: co_ai.agents.proximity.ProximityAgent
       enabled: true
       iterations: 1
     - name: reflection_delta
       cls: co_ai.agents.reflection_delta.ReflectionDeltaAgent
       enabled: true
       iterations: 1
     - name: mrq_strategy
       cls: co_ai.agents.mrq_strategy.MRQStrategyAgent
       enabled: true
       iterations: 1
