# config/config.yaml
defaults:
  - _self_
  - db: postgres
  - agents/dots_planner
  - agents/pipeline_judge
  - agents/proximity
  - agents/ranking
  - agents/refiner
  - agents/review
  - agents/scorer
  - agents/survey
  - agents/search_orchestrator
  - agents/method_planner
  - agents/idea_innovation
  - agents/idea_sharpening
  - agents/idea_evaluator
  - agents/idea_evolution
  - agents/knowledge_loader
  - logging/json_logger

# The goal of the pipeline, e.g., "Generate a hypothesis about the impact of climate change on biodiversity."
# This is a placeholder and should be replaced with the actual goal.
goal:
  goal_text: "Will AI ever be able to reprogram itself?"
  goal_type: "research"
  focus_area: "nlp"
  strategy: "literature_review"

dynamic:
  name: lookahead
  enabled: false
  cls: stephanie.agents.lookahead.LookaheadAgent

planner:
  name: planner
  enabled: false
  cls: stephanie.agents.planner.PipelinePlannerAgent
  dots_enabled: true
  lookahead_enabled: true


post_judgment:
  name: pipeline_judge
  enabled: false
  cls: stephanie.agents.pipeline_judge.PipelineJudgeAgent


paths:
  prompts: ${hydra:runtime.cwd}/prompts

report:
  generate_report: true
  path: ${hydra:runtime.cwd}/reports

web_search:
  engine: "searxng"
  instance_url: "http://localhost:8080"


embeddings:
  model: "mxbai-embed-large"
  dimension: 1024
  endpoint: "http://localhost:11434/api/embeddings"

pipeline:
  name: default_pipeline
  description: "NOVELSEEK pipeline for exploring the question: 'Will AI ever be able to reprogram itself?'"
  stages:
     - name: survey
       cls: stephanie.agents.survey.SurveyAgent
       enabled: true
       iterations: 1
     - name: search_orchestrator
       cls: stephanie.agents.search_orchestrator.SearchOrchestratorAgent
       enabled: false
       iterations: 1
     - name: knowledge_loader
       cls: stephanie.agents.knowledge_loader.KnowledgeLoaderAgent
       enabled: true
       iterations: 1
     - name: idea_innovation
       cls: stephanie.agents.idea_innovation.IdeaInnovationAgent
       enabled: true
       iterations: 1
     - name: idea_sharpening
       cls: stephanie.agents.idea_sharpening.IdeaSharpeningAgent
       enabled: true
       iterations: 1
     - name: ranking
       cls: stephanie.agents.ranking.RankingAgent
       enabled: true
       iterations: 1
     - name: idea_evaluator
       cls: stephanie.agents.idea_evaluator.IdeaEvaluatorAgent
       enabled: true
       iterations: 1
     - name: idea_evolution
       cls: stephanie.agents.idea_evolution.IdeaEvolutionAgent
       enabled: true
       iterations: 3
     - name: method_planner
       cls: stephanie.agents.method_planner.MethodPlannerAgent
       enabled: true
       iterations: 1
