# config/config.yaml
defaults:
  - _self_
  - db: postgres
  - agents/survey
  - agents/search_orchestrator
  - agents/knowledge_loader
  - agents/document_loader
  - agents/paper_score
  - agents/literature
  - agents/literature_ranking
  - agents/generation
  - logging/json_logger

goal:
  goal_text: "https://arxiv.org/pdf/2503.00735"
  focus_area: "similar_papers"
  goal_type: "similar_papers"
  goal_category: "ai_research"
  strategy: "reasoning"
  difficulty: "hard"
  expected_formats:
    - "tree_of_thought"
    - "strategy_plan"

post_judgment:
  name: pipeline_judge
  enabled: false
  cls: co_ai.agents.pipeline_judge.PipelineJudgeAgent

paths:
  prompts: ${hydra:runtime.cwd}/prompts

report:
  generate_report: true
  path: ${hydra:runtime.cwd}/reports

web_search:
  engine: "searxng"
  instance_url: "http://localhost:8080"


embeddings:
  model: "mxbai-embed-large"
  dimension: 1024
  endpoint: "http://localhost:11434/api/embeddings"

pipeline:
  name: papers
  description: "Default hypothesis generation and refinement pipeline"
  stages:
     - name: survey
       cls: co_ai.agents.knowledge.survey.SurveyAgent
       enabled: true
       iterations: 1
     - name: search_orchestrator
       cls: co_ai.agents.knowledge.search_orchestrator.SearchOrchestratorAgent
       enabled: true
       iterations: 1
     - name: document_loader
       cls: co_ai.agents.knowledge.document_loader.DocumentLoaderAgent
       enabled: true
       iterations: 1
