# config/config.yaml
defaults:
  - _self_
  - db: postgres
  - agents/generation
  - agents/general_reasoner
  - agents/score_analysis
  - agents/unified_mrq
  - logging/json_logger

goal:
  goal_text: "What is an effective method for teaching a small AI agent to generalize symbolic reasoning from a limited number of program examples?"
  goal_type: "research"
  goal_category: "ai_reasoning"
  strategy: "program_induction"
  difficulty: "hard"
  expected_formats:
    - "mechanism"
    - "algorithm"
    - "step_by_step"

paths:
  prompts: ${hydra:runtime.cwd}/prompts

report:
  generate_report: true
  path: ${hydra:runtime.cwd}/reports

web_search:
  engine: "searxng"
  instance_url: "http://localhost:8080"


embeddings:
  model: "mxbai-embed-large"
  dimension: 1024
  endpoint: "http://localhost:11434/api/embeddings"

pipeline:
  name: default_pipeline
  description: "Default hypothesis generation and refinement pipeline"
  stages:
    - name: general_reasoner
      cls: stephanie.agents.general_reasoner.GeneralReasonerAgent
      enabled: true
      iterations: 1
    - name: score_analysis
      cls: stephanie.agents.score_analysis.ScoreAnalysisAgent
      enabled: false
      iterations: 1
    - name: unified_mrq
      cls: stephanie.agents.unified_mrq.UnifiedMRQAgent
      enabled: true
      iterations: 1
