# config/config.yaml
defaults:
  - _self_
  - db: postgres
  - agents/literature
  - agents/literature_ranking
  - agents/prompt_tuning
  - agents/generation
  - agents/refiner
  - agents/review
  - agents/reflection
  - agents/ranking
  - agents/evolution
  - agents/meta_review
  - agents/proximity
  - agents/sharpening
  - agents/judge
  - agents/cot_generator
  - agents/general_reasoner
  - agents/cot_dspy_generator
  - agents/supervisor
  - logging/json_logger

# The goal of the pipeline, e.g., "Generate a hypothesis about the impact of climate change on biodiversity."
# This is a placeholder and should be replaced with the actual goal.
goal: 
  goal_text: "Will AI ever be able to reprogram itself?"
  goal_type: research # Options: math, science, commonsense, factoid, ethical, policy, planning, creative, other, research

paths:
  prompts: ${hydra:runtime.cwd}/prompts

report:
  generate_report: true
  path: ${hydra:runtime.cwd}/reports

web_search:
  engine: "searxng"
  instance_url: "http://localhost:8080"


embeddings:
  model: "mxbai-embed-large"
  dimension: 1024
  endpoint: "http://localhost:11434/api/embeddings"

pipeline:
  name: default_pipeline
  description: "Default hypothesis generation and refinement pipeline"
  stages:
    - name: general_reasoner
      cls: co_ai.agents.general_reasoner.GeneralReasonerAgent
      enabled: true
      iterations: 1
    # - name: ranking
    #   cls: co_ai.agents.ranking.RankingAgent
    #   enabled: true
    #   iterations: 1
