# config/config.yaml
defaults:
  - _self_
  - db: postgres
  - agents/generation
  - agents/reflection
  - logging/json_logger

goal:
  goal_text: "How can we teach a small language model to self-correct its own mistakes using only limited labeled data?"
  goal_type: "research"
  goal_category: "ai_self_improvement"
  strategy: "reflection"
  difficulty: "hard"
  expected_formats:
    - "short_cot"
    - "code"
    - "mechanism"

dynamic:
  name: lookahead
  enabled: false
  cls: stephanie.agents.lookahead.LookaheadAgent

planner:
  name: planner
  enabled: false
  cls: stephanie.agents.planner.PipelinePlannerAgent
  dots_enabled: true
  lookahead_enabled: true

post_judgment:
  name: pipeline_judge
  enabled: false
  cls: stephanie.agents.pipeline_judge.PipelineJudgeAgent


paths:
  prompts: ${hydra:runtime.cwd}/prompts

report:
  generate_report: true
  path: ${hydra:runtime.cwd}/reports

web_search:
  engine: "searxng"
  instance_url: "http://localhost:8080"


embeddings:
  model: "mxbai-embed-large"
  dimension: 1024
  endpoint: "http://localhost:11434/api/embeddings"

pipeline:
  name: default_pipeline
  description: "Default hypothesis generation and refinement pipeline"
  stages:
     - name: generation
       cls: stephanie.agents.generation.GenerationAgent
       enabled: true
       iterations: 1
     - name: reflection
       cls: stephanie.agents.reflection.ReflectionAgent
       enabled: true
       iterations: 1
