# config/config.yaml
defaults:
  - _self_
  - db: postgres
  - agents/cot_dspy_generator
  - agents/cot_generator
  - agents/debate
  - agents/dots_planner
  - agents/evolution
  - agents/general_reasoner
  - agents/generation
  - agents/generic
  - agents/judge
  - agents/literature
  - agents/literature_ranking
  - agents/lookahead
  - agents/meta_review
  - agents/mrq_strategy
  - agents/pipeline_judge
  - agents/prompt_tuning
  - agents/proximity
  - agents/ranking
  - agents/refiner
  - agents/reflection
  - agents/reflection_delta
  - agents/review
  - agents/scorer
  - agents/sharpening
  - agents/symbolic_optimizer
  - logging/json_logger

goal:
  goal_text: "If I was to develop a self improving process what would be the steps needed?"
  goal_type: "theoretical"
  goal_category: "ai_research"
  strategy: "reasoning"
  difficulty: "medium"
  expected_formats:
    - "short_cot"
    - "code"

symbolic:
  enabled: true  # set to false to skip symbolic rule application
  rules_file: "config/rules/rules.yaml"
  enable_db_rules: true # load rules from the database
  match_priority:
    - goal_id
    - pipeline_run_id
    - metadata
  metadata_match_mode: partial   # options: exact, partial, off
  allow_fallback: true           # if no ID matches, allow metadata fallback


#dynamic:
#  name: lookahead
#  enabled: false
#  cls: co_ai.agents.lookahead.LookaheadAgent

planner:
  name: planner
  enabled: false
  cls: co_ai.agents.planner.PipelinePlannerAgent
  dots_enabled: true
  lookahead_enabled: true


post_judgment:
  name: pipeline_judge
  enabled: true
  cls: co_ai.agents.pipeline_judge.PipelineJudgeAgent


paths:
  prompts: ${hydra:runtime.cwd}/prompts

report:
  generate_report: true
  path: ${hydra:runtime.cwd}/reports

web_search:
  engine: "searxng"
  instance_url: "http://localhost:8080"


embeddings:
  model: "mxbai-embed-large"
  dimension: 1024
  endpoint: "http://localhost:11434/api/embeddings"

pipeline:
  name: default_pipeline
  description: "Default hypothesis generation and refinement pipeline"
  stages:
      - name: generation
        cls: co_ai.agents.generation.GenerationAgent
        enabled: true
        iterations: 1
      - name: symbolic_optimizer
        cls: co_ai.agents.symbolic_optimizer.SymbolicOptimizerAgent
        enabled: true
        iterations: 1
    #  - name: proximity
    #    cls: co_ai.agents.proximity.ProximityAgent
    #    enabled: true
    #    iterations: 1
    #  - name: review
    #    cls: co_ai.agents.review.ReviewAgent
    #    enabled: true
    #    iterations: 1
    #  - name: review
    #    cls: co_ai.agents.review.ReviewAgent
    #    enabled: true
    #    iterations: 1
    #  - name: scorer
    #    cls: co_ai.agents.scorer.ScorerAgent
    #    enabled: true
    #    iterations: 1
