# config/config.yaml
defaults:
  - _self_
  - db: postgres
  - agents/survey
  - agents/search_orchestrator
  - agents/rule_mutation
  - agents/document_loader
  - agents/paper_score
  - agents/literature
  - agents/self_edit_generator
  - agents/literature_ranking
  - agents/document_profiler
  - agents/generation
  - agents/paper_score
  - logging/json_logger

goal:
  goal_text: Improve an AI system’s ability to diagnose its own reasoning failures in complex decision-making tasks. The system should be able to identify faulty assumptions, reflect on its process, and revise future behavior accordingly.
  goal_type: "capability"
  goal_category: "self_reflection"
  focus_area: "ai_research"
  strategy: "introspective_diagnostics"
  difficulty: "medium"
  expected_formats:
    - "critique_chain"
    - "reasoning_trace"
    - "reflective_plan"

symbolic:
  enabled: true
  rules_file: "config/rules/self_edit_generator_rules.yaml"
  enable_db_rules: false # load rules from the database
  match_priority:
    - goal_id
    - pipeline_run_id
    - metadata
  metadata_match_mode: partial   # options: exact, partial, off
  allow_fallback: true           # if no ID matches, allow metadata fallback


post_judgment:
  name: pipeline_judge
  enabled: false
  cls: stephanie.agents.pipeline_judge.PipelineJudgeAgent

paths:
  prompts: ${hydra:runtime.cwd}/prompts

report:
  generate_report: true
  path: ${hydra:runtime.cwd}/reports

web_search:
  engine: "searxng"
  instance_url: "http://localhost:8080"


embeddings:
  model: "mxbai-embed-large"
  dimension: 1024
  endpoint: "http://localhost:11434/api/embeddings"

pipeline:
  name: papers
  tag: "huggingface_related_papers import"
  description: "Import papers score and save them"
  stages:
       - name: rule_mutation
         cls: stephanie.agents.seal.rule_mutation.RuleMutationAgent
         enabled: true
         iterations: 1
    #  - name: survey
    #    cls: stephanie.agents.knowledge.survey.SurveyAgent
    #    enabled: true
    #    iterations: 1
    #  - name: search_orchestrator
    #    cls: stephanie.agents.knowledge.search_orchestrator.SearchOrchestratorAgent
    #    enabled: true
    #    iterations: 1
    #  - name: document_loader
    #    cls: stephanie.agents.knowledge.document_loader.DocumentLoaderAgent
    #    enabled: true
    #    iterations: 1
    #  - name: document_profiler
    #    cls: stephanie.agents.knowledge.document_profiler.DocumentProfilerAgent
    #    enabled: true
    #    iterations: 1
    #  - name: paper_score
    #    cls: stephanie.agents.knowledge.paper_score.PaperScoreAgent
    #    enabled: true
    #    iterations: 1
    #  - name: knowledge_loader
    #    cls: stephanie.agents.knowledge.knowledge_loader.KnowledgeLoaderAgent
    #    enabled: true
    #    iterations: 1
