# config/config.yaml
defaults:
  - _self_
  - db: postgres
  - agents/generation
  - agents/review
  - agents/unified_mrq
  - logging/json_logger

# The goal of the pipeline, e.g., "Generate a hypothesis about the impact of climate change on biodiversity."
# This is a placeholder and should be replaced with the actual goal.
goal:
  goal_text: "If I was to develop a self improving process what would be the steps needed?"
  goal_type: "research"
  focus_area: "ai_research"
  strategy: "reasoning"
  difficulty: "medium"
  expected_formats:
    - "short_cot"
    - "code"

symbolic:
  enabled: true  # set to false to skip symbolic rule application

#dynamic:
#  name: lookahead
#  enabled: false
#  cls: co_ai.agents.lookahead.LookaheadAgent

planner:
  name: planner
  enabled: false
  cls: co_ai.agents.planner.PipelinePlannerAgent
  dots_enabled: true
  lookahead_enabled: true


post_judgment:
  name: pipeline_judge
  enabled: false
  cls: co_ai.agents.pipeline_judge.PipelineJudgeAgent


paths:
  prompts: ${hydra:runtime.cwd}/prompts

report:
  generate_report: true
  path: ${hydra:runtime.cwd}/reports

web_search:
  engine: "searxng"
  instance_url: "http://localhost:8080"


embeddings:
  model: "mxbai-embed-large"
  dimension: 1024
  endpoint: "http://localhost:11434/api/embeddings"

pipeline:
  name: default_pipeline
  description: "Default hypothesis generation and refinement pipeline"
  stages:
#    - name: cot_generator
#      cls: co_ai.agents.cot_generator.ChainOfThoughtGeneratorAgent
#      enabled: true
#      iterations: 1
      - name: generation
        cls: co_ai.agents.generation.GenerationAgent
        enabled: true
        iterations: 1
      - name: review
        cls: co_ai.agents.review.ReviewAgent
        enabled: true
        iterations: 1
      - name: unified_mrq
        cls: co_ai.agents.unified_mrq.UnifiedMRQAgent
        enabled: true
        iterations: 1
    #  - name: proximity
    #    cls: co_ai.agents.proximity.ProximityAgent
    #    enabled: true
    #    iterations: 1
    #  - name: review
    #    cls: co_ai.agents.review.ReviewAgent
    #    enabled: true
    #    iterations: 1
    #  - name: scorer
    #    cls: co_ai.agents.scorer.ScorerAgent
    #    enabled: true
    #    iterations: 1
