# configs/pipeline.yaml
pipeline:
  goal: "Will a decrease in U.S. interest rates in Q4 2024 lead to higher retail earnings?"
  use_grafting: true
  run_id: "interest_retail_2024"

model:
  name: "ollama_chat/gemma"
  api_base: "http://localhost:11434"
  api_key: ""

modules:
  memory:
    type: VectorMemory
    database: co
    user: co
    password: co
    host: localhost

  agents:
    generation:
      enabled: true
    reflection:
      enabled: true
    ranking:
      enabled: true
    evolution:
      enabled: true
      use_grafting: true
    meta_review:
      enabled: true
