pipeline:
  goal: "Evaluate Q4 2024 income statement for trading signal"
  run_id: "q4_income_2024"
  use_grafting: true

defaults:
  - prompt_refiner: default

db:
  database: co
  user: co
  password: co
  host: localhost
  port: 5432


agents:
  generation:
    enabled: true
    model:
      name: ollama_chat/qwen2.5
      api_base: http://localhost:11434
      api_key: null
    prompt_template: |
      Generate 3 testable hypotheses for the following financial goal:
      {goal}
    prompt_mode: static

  reflection:
    enabled: true
    model:
      name: ollama_chat/qwen2.5
      api_base: http://localhost:11434
      api_key: null
    prompt_template: |
      Critique the following hypothesis for clarity, novelty, and testability:
      {hypothesis}
    prompt_mode: static

  ranking:
    enabled: true
    model:
      name: ollama_chat/qwen2.5
      api_base: http://localhost:11434
      api_key: null
    prompt_template: |
      You are a critical analyst. Compare the following two hypotheses:
      A: {hypothesis_a}
      Review: {review_a}
      B: {hypothesis_b}
      Review: {review_b}
      Which one is stronger? Respond with 'A' or 'B'.
    prompt_mode: static

  evolution:
    enabled: true
    use_grafting: true
    model:
      name: ollama_chat/qwen2.5
      api_base: http://localhost:11434
      api_key: null
    prompt_template: |
      Improve the following top-ranked hypotheses:
      {top_hypotheses}
    prompt_mode: static

  metareview:
    enabled: true
    model:
      name: ollama_chat/qwen2.5
      api_base: http://localhost:11434
      api_key: null
    prompt_template: |
      Summarize the following evolved hypotheses into a cohesive strategic direction:
      {evolved_hypotheses}
    prompt_mode: static
