# config/prompt_refiner/default.yaml
prompt_refiner:
  enabled: true
  model:
    name: ollama_chat/qwen3
    api_base: http://localhost:11434
    api_key: null
  max_bootstrapped_demos: 3
  max_labeled_demos: 5
