arxiv_search:
  name: arxiv_search
  enabled: true
  save_prompt: true
  save_context: true
  skip_if_completed: false
  
  year_start: 2024
  year_end: 2025
  category: cs.AI
  max_results: 50
  top_n: 10

  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null
  input_keys: ["goal"]
  output_key: search_results
  prompt_mode: file
  prompt_file: arxiv_search.txt