# configs/agents/document_loader.yaml

document_loader:
  name: document_loader
  enabled: true
  max_chars_for_summary: 16000
  summarize_documents: I
  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null
  input_key: search_results   # add nodes
  output_key: debate  # change
  prompt_mode: file
  prompt_file: summarize.txt

  preferences:
    - novelty_driven
    - feasibility_first
    - technical_precision
    - clarity
    - simplicity
