document_reward_scorer:
  name: document_reward_scorer
  enabled: true
  save_prompt: true
  save_context: true
  skip_if_completed: false
  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null
  input_keys: ["goal", "hypotheses"]
  output_key: document_reward_scorer
  prompt_mode: file
  prompt_file: document_reward_scorer.txt