mrq_trainer:
  name: mrq_trainer
  enabled: true
  save_prompt: true
  save_context: false
  skip_if_completed: false

  model_save_path: "${hydra:runtime.cwd}/models/documents"
  model_prefix: "document_rm_"

  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null

  input_keys: ["goal", "hypotheses"]
  output_key: mrq_trainer
  prompt_mode: file
  prompt_file: mrq_trainer.txt