# configs/agents/document_loader.yaml

document_loader:
  name: document_loader
  enabled: true

  top_k_domains: 3
  max_chars_for_summary: 16000
  summarize_documents: true

  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null
  input_key: search_results   # add nodes
  output_key: documents
  prompt_mode: file
  prompt_file: summarize.txt

  preferences:
    - novelty_driven
    - feasibility_first
    - technical_precision
    - clarity
    - simplicity

  domain_seeds:
    symbolic:
      - "Symbolic planning using language agents."
      - "Neuro-symbolic reasoning for AI alignment."
    alignment:
      - "Scalable oversight and alignment strategies."
      - "Training language models to be helpful and harmless."
    planning:
      - "Hierarchical reinforcement learning for agents."
      - "Planning with tree search and transformers."
    training:
      - "Instruction tuning for LLMs."
      - "DPO and reward modeling techniques."
    reasoning:
      - "Multi-step chain-of-thought reasoning."
      - "Self-reflection and hypothesis verification."
