document_mrq_inference:
  name: document_mrq_inference
  enabled: true
  save_prompt: true
  save_context: true
  skip_if_completed: false
  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null
  input_keys: ["goal", "hypotheses"]
  input_key: documents
  output_key: document_mrq_inference
  prompt_mode: file
  prompt_file: document_mrq_inference.txt