document_ebt_inference:
  name: document_ebt_inference
  model_path: "${hydra:runtime.cwd}/models"
  model_type: "ebt"
  evaluator: "ebt"
  target_type: "document"
  dimensions: 
    - "alignment"
    - "clarity"
    - "implementability"
    - "novelty"
    - "relevance"
  input_key: "documents"
  output_key: "document_ebt_inference"