epistemic_plan_executor:
  name: epistemic_plan_executor
  enabled: true
  save_prompt: true
  save_context: false
  skip_if_completed: false

  plan_timeout_seconds: 300 # Safety timeout
  
  dimensions: 
    - "alignment"
    - "clarity"
    - "implementability"
    - "novelty"
    - "relevance"

  sicql:
    name: epistemic_plan_executor_sicql
    model_type: sicql
    evaluator: sicql
    target_type: document
    dimensions: 
      - alignment
      - clarity
      - implementability
      - novelty
      - relevance


  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null
  input_keys: ["goal", "hypotheses"]
  input_key: documents
  output_key: epistemic_plan_executor
  prompt_mode: file
  prompt_file: epistemic_plan_executor.txt