epistemic_plan_hrm_trainer:
  name: epistemic_plan_hrm_trainer
  enabled: true
  save_prompt: true
  save_context: false
  skip_if_completed: false

  model_path: "${hydra:runtime.cwd}/models"
  model_type: hrm
  model_version: "v1"
  evaluator: hrm
  target_type: plan_trace


  export_dir: ${hydra:runtime.cwd}/reports/epistemic_plan_executor
  dimensions: 
    - alignment
    - clarity
    - implementability
    - novelty
    - relevance

  encoder:
    name: epistemic_trace_encoder
    input_dim: 256
    embedding_dim: 1024
    step_hidden_dim: 64
    stats_input_dim: 12
    stats_hidden_dim: 128
    final_dim: 256
    n_steps: 4
    n_stats: 2
    model_type: trace_encoder
    model_version: "v1"

  hrm:
    name: epistemic_plan_executor_hrm
    input_dim: 256
    h_dim: 256
    l_dim: 128
    output_dim: 1
    n_cycles: 4
    t_steps: 4
    lr: 0.001
    batch_size: 1
    epochs: 10
    model_type: hrm
    evaluator: hrm
    model_version: "v1"
    target_type: document
    dimensions: 
      - alignment
      - clarity
      - implementability
      - novelty
      - relevance

  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null
  input_keys: ["goal", "hypotheses"]
  input_key: documents
  output_key: epistemic_plan_hrm_trainer
  prompt_mode: file
  prompt_file: epistemic_plan_hrm_trainer.txt