evaluator:
  name: evaluator
  enabled: true
  save_prompt: true
  save_context: false
  skip_if_completed: false
  use_memory_for_fast_prompts: false

  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null

  input_keys: ["goal", "hypotheses"]
  output_key: evaluator
  prompt_mode: file
  prompt_file: evaluator.txt
