# config/agents/evolution.yaml
defaults:
  - /prompt_refiner/default

evolution:
  name: evolution
  enabled: true
  strategy: goal_aligned  # Options: goal_aligned, simplification, inspiration, out_of_the_box
  use_grafting: true
  save_prompt: true
  preferences: 
    - goal_consistency
    - testability
    - simplicity
  model:
    name: ollama_chat/qwen3
    api_base: http://localhost:11434
    api_key: null
  prompt_mode: file
  prompt_path: evolution_simplification.txt
