# config/agents/generation.yaml
defaults:
  - /prompt_refiner/default

generation:
  name: generation
  enabled: true
  save_prompt: true
  model:
    name: ollama_chat/qwen3
    api_base: http://localhost:11434
    api_key: null
  prompt_mode: file
  prompt_path: generation_hypothesis.txt  
  prompt_match_re: Hypothesis\s+\d+:\s+(.*?)(?=\nHypothesis\s+\d+:|\Z)
