# configs/agents/idea_innovation.yaml

idea_innovation:
  name: idea_innovation
  enabled: true
  save_prompt: true
  save_context: false
  skip_if_completed: false
  strategy:
  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null
  prompt_mode: file
  prompt_file: idea.txt
  input_keys: ["goal"]
  input_key:
  output_key: idea

