# configs/agents/proximity.yaml
defaults:
  - /prompt_refiner/disabled

judge:
  name: judge
  enabled: true
  save_prompt: true
  save_context: false
  skip_if_completed: false
  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null
  input_key: hypotheses   # add nodes
  output_key: judge  # change
  prompt_mode: file
  prompt_file: scientific_debate.txt
OK but how do I   strategy: scientific_debate
