# configs/agents/judge.yaml

judge:
  name: judge
  enabled: true
  save_prompt: true
  save_context: false
  skip_if_completed: false
  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null
  input_key: hypotheses   
  output_key: judge  
  prompt_mode: file
  prompt_file: scientific_debate.txt
  strategy: scientific_debate
