knowledge_db_loader:
  name: knowledge_db_loader
  description: "Load knowledge from the database into the system this uses the embeddings to do a similarty search retuns top_k documents"  
  enabled: true
  save_prompt: true
  save_context: true
  skip_if_completed: false

  top_k: 100
  include_full_text: true
  search_method: document

  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null

  input_keys: ["goal", "hypotheses"]
  input_key: goal
  output_key: documents

  prompt_mode: file
  prompt_file: knowledge_db_loader.txt