# configs/agents/knowledge_loader.yaml

knowledge_loader:
  name: knowledge_loader
  top_k: 10
  domain_threshold: 0.5
  include_full_text: false
  prefer_sections: true
  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null

  prompt_mode: file
  prompt_file: default.txt
  input_keys: ["goal"]

  output_key: knowledge
