# configs/agents/knowledge_loader.yaml

knowledge_loader:
  name: knowledge_loader
  enabled: true
  save_prompt: true
  save_context: false
  skip_if_completed: false
  strategy:
  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null
  prompt_mode: file
  prompt_file: default.txt
  input_keys: ["goal"]
  input_key:
  output_key: knowledge_base

