master:
  name: master
  enabled: true
  save_prompt: true
  save_context: true
  skip_if_completed: false
  use_memory_for_fast_prompts: false

  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null

  master_model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null

  input_keys: ["goal"]
  input_key: question
  output_key: master_answer
  prompt_mode: file
  prompt_file: master.txt
