# configs/agents/mrq_scoring.yaml

mrq_scoring:
  name: mrq_scoring
  enabled: true
  save_prompt: true
  save_context: false
  skip_if_completed: false
  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null
  input_keys: ["goal"]   # add nodes
  output_key: mrq_scoring  # change
  prompt_mode: file
  prompt_file: default.txt
