# config/agents/paper_score.yaml

paper_score:
  name: paper_score
  save_prompt: trueNo
  model:
    name: ollama_chat/qwen3
    api_base: http://localhost:11434
    api_key: null

  prompt_mode: file
  prompt_file: full_review.txt
  input_key: documents
  output_key: paper_score

  preferences:
    - goal_consistency
    - factual
    - reliable_source
    - simplicity