# config/agents/review.yaml

paper_score:
  name: paper_score
  enabled: true

  source: context
  batch_size: 10

  save_prompt: true
  save_context: true
  skip_if_completed: false

  strategy: summary  # Options: full, summay
  model:
    name: ollama_chat/qwen3
    api_base: http://localhost:11434
    api_key: null

  prompt_mode: file
  prompt_file: full_review.txt
  output_key: paper_score

  preferences:
    - goal_consistency
    - factual
    - reliable_source
    - simplicity