# config/agents/pipeline_comparison.yaml

pipeline_comparison:
  name: pipeline_comparison
  save_prompt: true
  strategy: full_review  # Options: initial, full, observation, deep_verification
  tags:
    - strategy_A
    - strategy_B
  model:
    name: ollama_chat/qwen3
    api_base: http://localhost:11434
    api_key: null
  prompt_mode: file
  prompt_file: judge.txt
  output_key: comparison
  preferences:
    - accuracy