policy_synthesis:
  name: policy_synthesis
  enabled: true
  save_prompt: true
  save_context: false # too big to save
  skip_if_completed: false

  high_error_threshold: 0.5
  low_error_threshold: 0.1
  low_correlation_threshold: 0.2
  misleading_uncertainty_correlation_threshold: -0.2


  sources_for_deep_analysis:
    - sicql
    - ebt

  ground_truth_source: llm

  report_output_dir: "${hydra:runtime.cwd}/reports/score_comparison"

  target_type: "document"
  dimensions: 
    - "alignment"
    - "clarity"
    - "implementability"
    - "novelty"
    - "relevance"


  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null
  input_keys: ["goal", "hypotheses"]
  input_key: documents
  output_key: policy_synthesis
  prompt_mode: file
  prompt_file: policy_synthesis.txt