protocol:
  name: protocol
  enabled: true
  protocol: "code_exec"
  save_prompt: true
  save_context: true
  skip_if_completed: false
  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null
  input_keys: ["goal", "hypotheses"]
  input_key: documents
  output_key: protocol
  prompt_mode: file
  prompt_file: protocol.txt