pupil:
  name: pupil
  enabled: true
  save_prompt: true
  save_context: false
  skip_if_completed: false
  use_memory_for_fast_prompts: false

  model:
    name: ollama/qwen:0.5b
    api_base: http://localhost:11434
    api_key: null

  pupil_model:
    name: ollama/phi4-mini
    api_base: http://localhost:11434
    api_key: null

  input_keys: ["goal"]
  input_key: question
  output_key: pupil_answer
  prompt_mode: file
  prompt_file: pupil.txt
