pupil:
  name: pupil
  enabled: true
  save_prompt: true
  save_context: true
  skip_if_completed: false
  model:
    name: ollama/qwen:0.5b
    api_base: http://localhost:11434
    api_key: null
  input_keys: ["goal"]
  output_key: pupil
  prompt_mode: file
  prompt_file: pupil.txt
