# config/agents/ranking.yaml

ranking:
  name: ranking
  enabled: true
  source: context
  batch_size: 10    # limit to process at a time

  tournament_type: elo
  initial_elo_score: 750
  max_comparisons: 6  # if using database will change


  save_context: true
  skip_if_completed: false

  # model
  model:
    name: ollama_chat/qwen3
    api_base: http://localhost:11434
    api_key: null

  # Required keys for the agent ot effectively process the context
  required_keys: ["goal", "hypotheses"]   # add nodes
  # Key that it will iterate over ot generate reflections
  input_key: hypotheses
  # Key that it store the results of those reflections
  output_key: ranking  # change

  # prompt
  save_prompt: true
  prompt_mode: file
  strategy: debate
  prompt_file: debate.txt
  # preferences
  preferences:
  - goal_consistency
  - biological_plausibility
  - experimental_validity
  - novelty
  - simplicity
