# config/agents/ranking.yaml
defaults:
  - /prompt_refiner/disabled

ranking:
  name: ranking
  enabled: true
  strategy: debate
  tournament_type: elo
  max_comparisons: 6
  save_prompt: true
  save_context: true
  skip_if_completed: true
  preferences:
    - goal_consistency
    - biological_plausibility
    - experimental_validity
    - novelty
    - simplicity
  model:
    name: ollama_chat/qwen2.5
    api_base: http://localhost:11434
    api_key: null
  prompt_mode: file
  prompt_path: ranking_debate.txt