# config/agents/refiner.yaml

refiner:
  name: refiner
  enabled: true
  source: database  # database or context
  batch_size: 10    # limit to process at a time

  save_prompt: true
  save_context: true
  skip_if_completed: false
  strategy : default
  model:
    name: ollama/qwen3
    api_base: http://localhost:11434/api/generate
    api_key: null
  prompt_mode: file
  prompt_file: sharpening.txt

  # Which agent and prompt to refine
  target_agent: generation
  preferences:
    - goal_consistency
    - simplicity