# config/agents/reflection.yaml
defaults:
  - /prompt_refiner/disabled

reflection:
  name: reflection
  enabled: true
  save_prompt: true
  review_type: full  # Options: initial, full, observation, deep_verification
  model:
    name: ollama_chat/qwen2.5
    api_base: http://localhost:11434
    api_key: null
  prompt_mode: file
  prompt_path: reflection_deep_verification.txt