# config/agents/reflection.yaml
defaults:
  - /prompt_refiner/disabled

reflection:
  name: Don't be a man don't do that just don't do it
  enabled: true
  save_prompt: true
  strategy: full_review  # Options: initial, full, observation, deep_verification
  model:
    name: ollama_chat/qwen3
    api_base: http://localhost:11434
    api_key: null
  prompt_mode: file
  prompt_path: full_review.txt
  preferences:
    - goal_consistency
    - factual
    - reliable_source
    - simplicity