scoring_memcube:
  name: scoring_memcube
  enabled: true
  save_prompt: true
  save_context: false
  skip_if_completed: false
  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null
  input_keys: ["goal", "hypotheses"]
  input_key: documents
  output_key: scoring_memcube
  prompt_mode: file
  prompt_file: scoring_memcube.txt

  mrq:
    name: scoring_memcube_mrq
    model_type: "mrq"
    evaluator: "mrq"
    target_type: "document"
    dimensions: 
      - "alignment"
      - "clarity"
      - "implementability"
      - "novelty"
      - "relevance"

  ebt:
    name: scoring_memcube_ebt
    model_type: "ebt"
    evaluator: "ebt"
    target_type: "document"
    dimensions: 
      - "alignment"
      - "clarity"
      - "implementability"
      - "novelty"
      - "relevance"

  llm:
    name: scoring_memcube_llm
    model_type: "llm"
    evaluator: "llm"
    target_type: "document"
    model:
      name: ollama/qwen3
      api_base: http://localhost:11434
      api_key: null
    dimensions: 
      - "alignment"
      - "clarity"
      - "implementability"
      - "novelty"
      - "relevance"
