scoring_policy:
  name: scoring_policy
  enabled: true
  save_prompt: true
  save_context: false
  skip_if_completed: false

  target_type: "document"
  dimensions: 
    - "alignment"
    - "clarity"
    - "implementability"
    - "novelty"
    - "relevance"

  training_buffer_path: "${hydra:runtime.cwd}/logs/ebt_training.jsonl"


  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null
  input_keys: ["goal", "hypotheses"]
  input_key: documents
  output_key: scoring_policy
  prompt_mode: file
  prompt_file: scoring_policy.txt