worldview_pipeline_runner:
  name: worldview_pipeline_runner
  enabled: true
  save_prompt: true
  save_context: false
  skip_if_completed: false

  pipeline_registry_path: ${hydra:runtime.cwd}/config/registry/pipeline_registry.yaml


  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null
  
  input_keys: ["goal", "hypotheses"]
  output_key: world_create
  prompt_mode: file
  prompt_file: world_create.txt